[package]
name = "pyuuid"
version = "0.1.0"
edition = "2021"

[lib]
name = "_pyuuid"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "pyuuid._pyuuid"

[dependencies]
pyo3 = { version = "0.18.1", features = ["extension-module"] }
uuid = { version = "1.3.0", features = ["v1", "v3", "v4", "v5", "v6", "v7", "v8", "fast-rng"]}
